{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  labels:
    {{ include "app.labels" . | nindent 4 }}
data:
  {{ .Values.configMap.data | toYaml | nindent 2 }}
{{- end }}