{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secretName" . }}
  labels:
    {{ include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.stringData | toYaml | nindent 2 }}
{{- end }}